name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: false
          tags: localhost/postiz:latest

      - name: Save Docker image
        run: docker save -o postiz-image.tar localhost/postiz:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: postiz-image
          path: postiz-image.tar